# Generated by Django 4.2.7 on 2023-11-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, primary_key=False, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(primary_key=True,max_length=200),
        ),
    ]
