# Generated by Django 4.2.7 on 2023-11-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UplodedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=128)),
                ('Place', models.CharField(max_length=128)),
                ('Time', models.TimeField(max_length=128)),
                ('Date', models.DateField(blank=True)),
                ('Description', models.CharField()),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
